//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_calculation_data_table
    {
        public string Token_Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Billing_Token_Number { get; set; }
        public string Billing_Number { get; set; }
        public System.DateTime Bill_Date { get; set; }
        public decimal Billing_Total_amount { get; set; }
        public decimal Billing_Amount_paid { get; set; }
        public decimal Billing_Balance { get; set; }
        public string Order_Token_Number { get; set; }
        public string Order_Number { get; set; }
        public System.DateTime Order_Date { get; set; }
        public decimal Order_Total_amount { get; set; }
        public decimal Order_Amount_paid { get; set; }
        public decimal Order_Balance { get; set; }
        public string Other_expense_Token_number { get; set; }
        public decimal Other_expense_amount { get; set; }
        public System.DateTime Other_expense_Date { get; set; }
        public string Other_expense_ExpenseId { get; set; }
        public string Product_expense_Token_number { get; set; }
        public decimal Product_expense_Amount_for_expense { get; set; }
        public System.DateTime Product_expense_Date { get; set; }
        public string Product_expense_ExpenseId { get; set; }
        public string Employee_salary_expense_Token_number { get; set; }
        public decimal Employee_salary_expense_salary_to_be_paid { get; set; }
        public System.DateTime Employee_salary_expense_Date { get; set; }
        public string Employee_salary_expense_ExpenseId { get; set; }
        public string BillBy { get; set; }
    }
}
