//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Token_number { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Phone_number { get; set; }
        public string Address { get; set; }
        public string Vehicle_type { get; set; }
        public string Vehicle_number { get; set; }
        public string Mac_id { get; set; }
        public string User_Id { get; set; }
        public string User_name { get; set; }
    }
}
