//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Token_number { get; set; }
        public string Employee_Id { get; set; }
        public string Employee_name { get; set; }
        public string Designation { get; set; }
        public System.DateTime Joining_date { get; set; }
        public string Contact_number { get; set; }
        public string Email_id { get; set; }
        public decimal Salary { get; set; }
        public Nullable<System.DateTime> Leaving_date { get; set; }
        public bool login_required { get; set; }
        public System.DateTime Date { get; set; }
        public string Mac_id { get; set; }
        public string Image_path { get; set; }
        public string Password { get; set; }
        public string User_Id { get; set; }
        public string User_name { get; set; }
    }
}
