//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string Token_number { get; set; }
        public string Manager_name { get; set; }
        public string Email_Id { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> State_Code { get; set; }
        public string Pan_Number { get; set; }
        public bool IsActive { get; set; }
        public string Verification_code { get; set; }
        public string State_Name { get; set; }
    }
}
