//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_expense
    {
        public string Token_number { get; set; }
        public string Other_expense_type { get; set; }
        public decimal Other_expense_amount { get; set; }
        public System.DateTime Date { get; set; }
        public string ExpenseId { get; set; }
        public string Mac_id { get; set; }
        public string User_Id { get; set; }
        public string User_name { get; set; }
    }
}
