//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products_For_Sale
    {
        [Display(Name = "Token")]
        public string Token_Number { get; set; }
        [Display(Name = "Company Token")]
        public string Product_Token { get; set; }
        [Display(Name = "Company name")]

        public string Product_name { get; set; }

        public int Pieces { get; set; }
        [Display(Name = "Amount including tax")]
        public decimal Amout_after_tax { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Total amount should not be empty")]
        public decimal Total { get; set; }
        [Display(Name = "Tyre size")]

        public string Tyre_Size { get; set; }
        [Display(Name = "Supplier token")]

        public string Supplier_token { get; set; }
        [Display(Name = "Supplier name")]

        public string Supplier_name { get; set; }

        public System.DateTime Date { get; set; }
        [Display(Name = "Purchase price")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Purchase price should not be empty")]
        public decimal Purchase_Price { get; set; }

        public decimal CGST { get; set; }

        public decimal SGST { get; set; }
        [Display(Name = "Administrator Token number")]
        public string Administrator_Token_number { get; set; }
        [Display(Name = "Administrator name")]
        public string Administrator_name { get; set; }
        [Display(Name = "Approve date")]
        public System.DateTime Approve_date { get; set; }
        public bool Approve { get; set; }
        [Display(Name = "Selling price")]
        //[Range(1,9999999,ErrorMessage ="Selling price cannot be less that 1 or greater than 9999999")]

        public decimal Selling_Price { get; set; }
        public int StockIn { get; set; }

        public decimal Up_Selling_Price { get; set; }

        public decimal Up_CGST { get; set; }

        public decimal Up_SGST { get; set; }
        [Display(Name = "Delivery contact number")]

        public long Delivery_contact_number { get; set; }
        [Display(Name = "Delivery address")]


        public string Delivery_address { get; set; }
        [Display(Name = "Item Id")]

        public string Item_tyre_Id { get; set; }
        [Display(Name = "Invoice number")]

        public string Purchase_number { get; set; }
        [Display(Name = "Invoice date")]

        public System.DateTime PurchaseDate { get; set; }
        [Display(Name = "Tyre make")]

        public string Tyre_make { get; set; }
        [Display(Name = "Tyre type")]

        public string Tyre_type { get; set; }
        [Display(Name = "Tyre feel")]

        public string Tyre_feel { get; set; }
        public string Vehicle_Token { get; set; }
        [Display(Name = "Vehicle type")]
        public string Vehicle_type { get; set; }
        public string Description { get; set; }
        public string Tyre_token { get; set; }
        public string Item_tyre_token { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Mac_id { get; set; }

        public Nullable<bool> requestsend { get; set; }
        public string rateperunit { get; set; }
        public bool Totalamount { get; set; }
        public string percent { get; set; }
        public bool amnt { get; set; }

        public decimal Selling_CGST { get; set; }
        public decimal Selling_SGST { get; set; }
        public Nullable<bool> CGST_SGST_CHECK { get; set; }


        public string User_Id { get; set; }
        public string User_name { get; set; }
        public string Approve_user_id { get; set; }
        public string Approve_user_name { get; set; }
        public string Rate_update_user_id { get; set; }
        public string Rate_update_user_name { get; set; }
        public decimal Total_discount { get; set; }
        public decimal Total_amount { get; set; }
        public decimal Amount_paid { get; set; }
        public decimal Balance { get; set; }
        public string Mode_of_payment { get; set; }
        public string Narration { get; set; }
        public string CustToken_number { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Phone_number { get; set; }
        public string Address { get; set; }
        public string Vehicle_number { get; set; }
        public string Billno { get; set; }
        public string selectionForExecution { get; set; }

        public string Tyre_number { get; set; }

        public bool IsGstPercent { get; set; }
        public bool CalculationByRatePerUnit { get; set; }

        public Nullable<decimal> Selling_net_total { get; set; }
        public System.DateTime SDate { get; set; }
        public System.DateTime EDate { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}



