//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Detail
    {
        public int Quotation_details_number { get; set; }
        public string Quotation_Token_number { get; set; }
        public string Quotation_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Selling_item_token { get; set; }
        public int Pieces { get; set; }
        public decimal Amount { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public decimal Sub_Total { get; set; }
        public string Selling_item_id { get; set; }
        public Nullable<bool> IsGstPercent { get; set; }
    }
}
