//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Master
    {
        public string Token_Number { get; set; }
        public string Quotation_Number { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total_tax { get; set; }
        public decimal Rate_including_tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Total_discount { get; set; }
        public decimal Total_amount { get; set; }
        public bool Discountper { get; set; }
        public string Narration { get; set; }
        public string Mac_id { get; set; }
        public string User_Id { get; set; }
        public string User_name { get; set; }
        public string Transaction_Id { get; set; }
        public string Customer_token_number { get; set; }
        public Nullable<bool> IsGstPercent { get; set; }
    }
}
