//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_update_Backup
    {
        public string Token_number { get; set; }
        public string Item_number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Date_of_stock_entry { get; set; }
        public Nullable<decimal> Selling_rate { get; set; }
        public Nullable<decimal> Selling_CGST { get; set; }
        public Nullable<decimal> Selling_SGST { get; set; }
    }
}
