//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockForBillingRPT
    {
        public string Token_Number { get; set; }
        public string Product_name { get; set; }
        public string Tyre_Size { get; set; }
        public decimal Selling_Price { get; set; }
        public string Item_tyre_Id { get; set; }
        public decimal Selling_CGST { get; set; }
        public decimal Selling_SGST { get; set; }
    }
}
